apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-operator
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cat-operator
  template:
    metadata:
      labels:
        app: cat-operator
    spec:
      serviceAccountName: my-operator
      containers:
        - name: cat-operator
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
